/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch tokens
        'inverse-on-surface': '#eff1f4',
        'secondary-container': '#d2e2ee',
        secondary: '#51606b',
        'inverse-surface': '#2d3133',
        'secondary-fixed': '#d5e5f1',
        'primary-fixed-dim': '#b9c7e4',
        'on-secondary': '#ffffff',
        primary: '#0d1c32',
        'surface-container-high': '#e6e8eb',
        'primary-container': '#0d1c32',
        'surface-container': '#eceef1',
        'on-primary-fixed-variant': '#39475f',
        'primary-fixed': '#d6e3ff',
        'on-surface': '#191c1e',
        tertiary: '#0d1c32',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#191c1e',
        'error-container': '#ffdad6',
        'outline-variant': '#c5c6cd',
        'on-secondary-fixed-variant': '#3a4953',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#b9c9d5',
        surface: '#f7f9fc',
        'tertiary-fixed-dim': '#66dd8b',
        outline: '#75777e',
        'surface-bright': '#f7f9fc',
        'on-tertiary-fixed': '#00210c',
        'on-secondary-container': '#55656f',
        'surface-tint': '#515f78',
        'on-surface-variant': '#44474d',
        'on-tertiary-fixed-variant': '#005227',
        'surface-container-low': '#f2f4f7',
        'surface-dim': '#d8dadd',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        error: '#ba1a1a',
        background: '#f7f9fc',
        'surface-variant': '#e0e3e6',
        'on-tertiary-container': '#08984e',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#0d1c32',
        'on-secondary-fixed': '#0e1d26',
        'tertiary-fixed': '#83fba5',
        'tertiary-container': '#00210c',
        'on-primary-container': '#76849f',
        'inverse-primary': '#b9c7e4',
        // Faculty accents
        'faculty-law': '#1e40af',
        'faculty-econ': '#047857',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        round: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '20px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        base: '4px',
      },
      fontFamily: {
        body: ['Assistant', 'Heebo', 'system-ui', 'sans-serif'],
        display: ['Heebo', 'Assistant', 'system-ui', 'sans-serif'],
        caption: ['Assistant', 'system-ui', 'sans-serif'],
        'display-lg': ['Heebo', 'system-ui', 'sans-serif'],
        'label-caps': ['Assistant', 'system-ui', 'sans-serif'],
        'title-sm': ['Heebo', 'system-ui', 'sans-serif'],
        'body-lg': ['Assistant', 'system-ui', 'sans-serif'],
        'headline-md': ['Heebo', 'system-ui', 'sans-serif'],
        'body-md': ['Assistant', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
      },
      boxShadow: {
        card: '0px 4px 12px rgba(10, 25, 47, 0.05)',
        'card-hover': '0px 8px 24px rgba(10, 25, 47, 0.08)',
      },
    },
  },
  plugins: [],
};
